name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  # Optionally, you can trigger on pull_request or schedule

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # (Optional) Display disk usage before build (for debugging)
    - name: Check disk space before build
      run: df -h

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Cache Docker layers to speed up builds and reduce repeated downloads
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/flux_ns:latest
          ${{ secrets.DOCKER_USERNAME }}/flux_ns:${{ github.sha }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    # (Optional) Clean up unused Docker objects to free space
    - name: Clean up Docker system
      run: docker system prune -af

    # (Optional) Display disk usage after build (for debugging)
    - name: Check disk space after build
      run: df -h
